### ISSUE TITLE
Couldn't we find better names for TEnv and term_env?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#124]
Moreover, comments do not speak of term environments but of higher-order terms, but this is not the only place where there are higher-order terms...

https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/terms.ml#L49

It looks like term_env (in the case TE_Some) corresponds to the notion of "substitute" in CRSs  (see http://doi.org/10.1016/0304-3975(93)90091-7) . TEnv is something else:

https://github.com/Deducteam/lambdapi/blob/8060eee5a306ff4dd13291876e459c9a23c1e65f/src/terms.ml#L31

It seems to be just an application, leading to a beta development.

So, would it be better to rename term_env as substitute, and TEnv as something like SubApp?

**Comment by rlepigre** [comment]
Well, the spirit of that constructor is really that you have a term in some environment. Or said otherwise, and open term with value assigned for each of its free variables. And in a way, an environment and a substitution are really similar objects. Maybe we should discuss these renaming things in person.

**Comment by rlepigre** [comment]
I think this has been clarified by the documentation modifications I did.
