### ISSUE TITLE
Valid inference rule for the product ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#140]
https://github.com/Deducteam/lambdapi/blob/609164c8db277bc7e7c3974a41f731868af464e0/src/typing.ml#L66

The current code means that, if b is of type a metavariable X, then X must be set to TYPE. Why couldn't it be set to KIND? Perhaps, we need to explicit some invariant here about the type of metavariables.

**Comment by rlepigre** [comment]
Here there are two choices:
 - failing with a message like `missing type annotation`
 - trying to make a sensible choice between `TYPE` and `KIND`.

I think it makes sense to choose `TYPE` because it is most likely to have been omitted by the user. So an invariant could be: _if you meant `KIND`, you should have said so_.

**Comment by FranckS** [comment]
I don't get it, why couldn't we try the conversion between [s] and [Type], and if it fails the conversion between [s] and [Kind] instead of failing or making a choice ?

**Comment by rlepigre** [comment]
We have to make a choice here because the sort is not constrained by type-checking. What happens here is that we learn learn a new constraint: either `s = TYPE` or `s = KIND`. It could be possible to include some logical structure (e.g., disjonction) in our set of constraints, but solving them would then require backtracking. This would introduce both inefficiency and a lack of predictability.

Anyway, when you infer the sort of a product, you recursively infer the sort of its co-domain. If the sort is `KIND` then the chain usually ends with `TYPE`, and then you fall back into the case where `s` is equal to `KIND`. That is why I think that adding the constraint `s = TYPE` is a better choice when no sort has been inferred.

**Comment by fblanqui** [comment]
'conv s Type' will instantiate s with Type if s is a metavariable. You 
cannot know at this point whether it is a good choice or not. If there 
really is a choice to do here, then we must implement some 
back-tracking... I prefer not to do that.

Le 08/02/2019 à 22:42, FranckS a écrit :

**Comment by fblanqui** [comment]
Currently, two kinds of metavariables are generated in scoping. To replace _ in a domain position, we generate a metavariable N of type TYPE in some context, that is, N : (x1:T1)..(xn:Tn)TYPE and N[x1,..,xn] : TYPE. Otherwise, we generate a metavariable M of type a metavariable N of the first kind, that is, M : (x1:T1)..(xn:Tn)N[x1,..,xn] and M[x1,..,xn] : N[x1,..,xn] : TYPE.

When trying to infer the type of an application tu in the context x1:T1,..,xn:Tn and the whnf infered type c of t is not a product, we generate a constraint c = ∀x:A[x1,..,xn].B[x1,..,xn,x] where A[x1,..,xn] : A' : TYPE and B[x1,..,xn] : B' : TYPE.

Similarly, when trying to check that λx:t.u is of whnf type c and c is not a product, we generate a constraint c = ∀x:t.B[x1,..,xn,x] where B[x1,..,xn,x] : B' : TYPE.

Here, we can make several remarks:
- Because they are declared of arity 0, the new metas A' and B' cannot depend on x1,..,xn.
- A' is useless as it can only be equal to TYPE. (Hence, the type of A' is wrong: it should be KIND.)
- B' can be equal to TYPE or KIND only. In the first case, its type is KIND (and not TYPE). In the second case, it is not typable.

Perhaps, we should add a flag to metas to indicate when they can only be instantiated by a sort.

**Comment by fblanqui** [comment]
Remark: the type field of a meta can be invalid. When B'=KIND, then B is of type (x1:T1)..(xn:Tn)(x:A[x1,..,xn])KIND, which is invalid.

**Comment by fblanqui** [comment]
Remark: if B'=KIND, then B[x1,..,xn,x] can only be of the form ∀y1:U1,..,∀yk:Uk,TYPE.

**Comment by fblanqui** [comment]
As terms of type KIND can only be of the form ∀y1:U1,..,∀yk:Uk,TYPE, before chosing TYPE for ∀x:a,b, we could check whether b is of the form ∀y1:U1,..,∀yk:Uk,TYPE, in which case we could return KIND instead.

**Comment by fblanqui** [comment]
But, as already mentioned by Rodolphe previously, if b is of the form ∀y1:U1,..,∀yk:Uk,TYPE, then s is equal to KIND. So, indeed, there is no other possible choice than setting s to TYPE. So, we can close this issue. I'm just going to add some comment in the code to clarify this point.

**Comment by fblanqui** [comment]
Wait, if [s] is not a sort, then we could be in the case where [b] is a metavariable and [s] is a metavariable too. In this case, after https://github.com/Deducteam/lambdapi/issues/195#issue-420632861, [s] can be of type [Type] or be a sort. If [s] is of type [Type], then it would be better to fail right away instead of instantiating [s] to some sort. And if [s] is not of type [Type], we still have the possibility that [s] could be set to [Kind], and [b] to a kind. When can this happen?

**Comment by rlepigre** [comment]
Well, if `s` is not a sort then the term is ill-typed. The type of a product is always `TYPE` of `KIND`, right?

**Comment by fblanqui** [comment]
The (potential) problem is when b and s are metavariables.

**Comment by rlepigre** [comment]
I think that if there is a problem then it is not here: whatever `b` is, the product `Ɐ(x:a), b` must have type `TYPE` or `KIND`. Maybe the expression that is being type is not typable overall, but the local decision we make is definitely not wrong.

**Comment by fblanqui** [comment]
I am not convinced. As said, why couldn't we instantiate s by KIND and b by a kind? Hence my question: can this happen?

**Comment by rlepigre** [comment]
I would say no because I don't see how `KIND` would fail to be inferred. It only appears when we check the sort of the type of a declared symbol, and we can never omit to give the type of a symbol. And in the case where the sort is `KIND`, then the type is of the form `Ɐ(x1:a1) ... (xn:an), TYPE`. So yeah, I think we will always be able to infer `KIND` when the sort is `KIND`.

The only potentially tricky case is when you do something like:
```
symbol const N : _
// The type of N should be TYPE
```
But I don't see why we would expect the metavariable to be inferred in such a case.

**Comment by fblanqui** [comment]
Right, no kind can occur inside an object-level or type-level term (type-level in the sense of being of type TYPE).
