### ISSUE TITLE
Allowing unicode symbols in identifiers

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#150]
ℕ is not accepted as identifier:

symbol ℕ : TYPE

[tests/OK/infix.lp, 1:7] Parse error.

**Comment by rlepigre** [comment]
Unicode is a quite complex matter when it comes to identifiers... From my point of view it is reasonable to stick to the simple use that we have. Note that you can still use the following.
```
symbol {|ℕ|} : TYPE
```

**Comment by fblanqui** [comment]
I know but it is not convenient at all. With respect to this, we should 
definitely try to follow Agda. Why would it be difficult to handle 
unicode caracters in identifiers?

Btw, what's the role of KW in parser.ml?

Le 12/02/2019 à 18:18, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
Unicode is hard for several reasons, but the main one is that this may introduce bad behaviors when combined with infix symbols. To solve this problem, Agda uses a very strong lexical convention, which enforces putting spaces everywhere (you cannot write `n+m`, you always need to write `n + m`, otherwise the code is understood as an identifier called `"n+m"`). I'd rather not go down the same road...

One thing we could do though, is select a set of unicode identifiers that are likely to be used (for example all the `\mathbb` series), and even do other things like allowing identifiers to be terminated by a subscript. Alternatively, we could add a way to _declare_ identifiers, so that the user can say "from now on, I'm going to use `ℕ` as an identifier".

The role of `KW` is to reserve keywords, so that they cannot be considered identifiers.

**Comment by fblanqui** [comment]
Le 12/02/2019 à 18:56, Rodolphe Lepigre a écrit :
>
> Unicode is hard for several reasons, but the main one is that this may 
> introduce bad behaviors when combined with infix symbols.
>
Could you please give some example?


> To solve this problem, Agda uses a very strong lexical convention, 
> which enforces putting spaces everywhere (you cannot write |n+m|, you 
> always need to write |n + m|, otherwise the code is understood as an 
> identifier called |"n+m"|). I'd rather not go down the same road...
>
> One thing we could do though, is select a set of unicode identifiers 
> that are likely to be used (for example all the |\mathbb| series), and 
> even do other things like allowing identifiers to be terminated by a 
> subscript. Alternatively, we could add a way to /declare/ identifiers, 
> so that the user can say "from now on, I'm going to use |ℕ| as an 
> identifier".
>
Would it scale up?

Would another option be to restrict the set of *infix* identifiers?

**Comment by rlepigre** [comment]
> Could you please give some example?

I gave one above already with `"n+m"`, but imagine you have defined a notation for the set of natural numbers, then if you define some theorem called `"blaℕbla"` then you won't know whether to parse that as `"bla"` applied to `"ℕ"` and `"bla"`or a single identifier.

>> One thing we could do though, is select a set of unicode identifiers that are likely to be used (for example all the `\mathbb` series), and even do other things like allowing identifiers to be terminated by a subscript. Alternatively, we could add a way to _declare_ identifiers, so that the user can say "from now on, I'm going to use |ℕ| as an identifier"

> Would it scale up?

Yes, I think so, if we combine the two and propose some identifiers by default. Note that I here assume that people won't want identifiers written in another alphabet (e.g., using Chinese characters), which I think is reasonable.

> Would another option be to restrict the set of *infix* identifiers?

In any case, yes. It is currently the responsibility of the user to restrict the infix symbols he or she defines, so that parsing is not completely broken. Currently, it is possible to define the infix symbol `"symbol"`, or the infix symbol "`λ`", which would completely break parsing by introducing ambiguities. And they would be resolved rather randomly.

**Comment by fblanqui** [comment]
Rodolphe, could you implement identifier declarations?

And what about forbidding to use keywords as infix identifiers?

**Comment by rlepigre** [comment]
I don't have much time to do that right now, but I'll have a shot before the end of the month. Keywords are not the only problematic things in infix identifier, there are reserved symbols that should be rejected as well. I'll try to come up with a solution to that at the same time, keeping in mind that the set of valid infix symbols should be disjoint from the set of valid identifiers (plus keywords and some symbols like parentheses, and every other symbols appearing in the grammar).

**Comment by rlepigre** [comment]
It would be great if you could make a list of symbols that you think should be recognized as standalone identifiers (e.g., `"ℕ"`). This list will of course be configurable in some way, but symbols provided by defaults would be a good starting point to see what we want to go toward. And this will need to be done anyway.

If you come up with (part of) such a list, paste it in this issue, and everyone can of course participate / suggest extensions.

**Comment by fblanqui** [comment]
We also need to allow subscripts, and this could be recursive: 
\alpha_{\alpha_0}.

Le 13/02/2019 à 16:29, Frédéric Blanqui a écrit :

**Comment by fblanqui** [comment]
Useful web sites:

https://unicode-table.com/en/

https://unicode-table.com/en/#mathematical-operators

https://unicode-table.com/en/#miscellaneous-mathematical-symbols-a

https://unicode-table.com/en/#arrows

https://unicode-table.com/en/#suplemental-arrows-a

https://unicode-table.com/en/#suplemental-arrows-b


Le 13/02/2019 à 16:37, Frédéric Blanqui a écrit :

**Comment by fblanqui** [comment]
Unicode subscripts and superscripts: 
https://unicode-table.com/en/blocks/superscripts-and-subscripts/

Le 13/02/2019 à 16:37, Frédéric Blanqui a écrit :

**Comment by rlepigre** [comment]
What I'm for is a list of about 200 characters that we would want to allow as identifiers by default. Other, less useful (because less common) characters would then be added through manual configuration in a given Lambdapi development. Note that I am here talking about identifiers, not infix symbols. Infix symbols will never be predefined in the system, we will only have a blacklist of forbidden infix operator. Here we want to construct a list of identifiers, that can be used as symbol name or variable name.

For instance, our list could contain: ℕ and similar symbols, Greek letters (but obviously not λ), and support for integer subscript.

Note that we cannot really hope to get a general subscript / superscript mechanism because they cannot be represented in text editors.

**Comment by fblanqui** [comment]
https://unicode-table.com/en/search/?q=double+struck
https://unicode-table.com/en/search/?q=greek+letters

**Comment by fblanqui** [comment]
@rlepigre : would you have some time to work on this?

**Comment by rlepigre** [comment]
@fblanqui: not right now, and probably not before a couple of weeks. I don't see that as a critical feature, so it is quite low in my "todo list".

**Comment by rlepigre** [comment]
It is now possible (since 36265b61114e04c70cc3678789a92a54aa2c5d6d) to declare identifiers, in particular identifiers including unicode characters. For instance, you can do the following.
```
set declared "ℕ"
set declared "n₁"
set declared "n₂"

symbol ℕ : TYPE

definition fst : ℕ ⇒ ℕ ⇒ ℕ ≔ λ n₁ n₂, n₁
definition snd : ℕ ⇒ ℕ ⇒ ℕ ≔ λ n₁ n₂, n₂
```
This seems like a reasonable approach to me (at least for a while), so I'll close the issue. Note that we can define a file `stdlib/symbols.lp` containing something like the following.
```
set declared "ℕ"
set declared "α"
set declared "β"
set declared "γ"
...
```
And then to be able to use all these symbols in your development you only need to do `require open stdlib.symbols`.
