### ISSUE TITLE
add grammar entries for infer, whnf and nf

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#152]
In LP, there is currently nothing corresponding to the Dedukti commands #INFER and #WHNF. We can only assert equivalences and typing constraints. It would be useful for debugging purposes. The code is already here in handle.ml (and used when reading Dedukti files). We just need to add some grammar entries in parser.ml. What about "infer", "whnf" and "nf"?

**Comment by fblanqui** [comment]
including step counts (was https://github.com/Deducteam/lambdapi/issues/21).

**Comment by rlepigre** [comment]
For the record, I abandoned the idea of having a step count because it harms efficiency. Moreover, it is not really clear what counting steps means given our reduction strategy (and the sharing of evaluation during matching). Maybe decision trees will help on that front.

Overall, I'm not sure if step counting is really useful in practice.

**Comment by fblanqui** [comment]
We can give it whatever semantics we want. For instance, counting the 
number of rewrite steps whatever when and why they are for. Then, it 
should not affect the efficiency too much (it just increments a counter 
when a rewrite rule is applied). It provides a way to limit the number 
of rewrite steps. It could be useful in some tactics. So, we should 
implement it only if it is really useful to someone.

**Comment by fblanqui** [comment]
Done in https://github.com/Deducteam/lambdapi/commit/1b3c78cd771c43911086060777a5841d3b3d43a4.
