### ISSUE TITLE
Problem with binary operator priorities?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#182]
```
// Type of natural numbers

symbol const N : TYPE

symbol const z : N
symbol const s : N ⇒ N

// Enabling builtin natural number literals

set builtin "0"  ≔ z
set builtin "+1" ≔ s

definition forty_two ≔ 42

// Addition

symbol add : N ⇒ N ⇒ N set infix left 6 "+" ≔ add

rule z      + &n     → &n
 and (s &m) + &n     → s (&m + &n)
 and &m     + z      → &m
 and &m     + (s &n) → s (&m + &n)

// Multiplication

symbol mul : N ⇒ N ⇒ N set infix left 7 "×" ≔ mul

rule z      × _      → z
 and (s &m) × &n     → &n + &m × &n
 and _      × z      → z
 and &m     × (s &n) → &m + &m × &n

assert ∀x y z,x+y×z ≡ ∀x y z,x+(y×z) // fails
```

Changing the priority of mul to 5 yields the same result.

**Comment by rlepigre** [comment]
This is not a parsing problem at all, please do some investigation before posting issues. Here the problem comes from the fact that different metavariables are generated for the domains. I changed the code (see e0d6ef215de73ea8aa0bf11dcc9475a86032d322) so that we now infer types for the left hand side and right hand side of the equivalence when checking convertibility. And we also check convertibility between types.

Note that in your example, you probably meant to use lambdas, not quantifiers. Otherwise this is not well-typed. Or you need to insert an predicate.
