### ISSUE TITLE
Using OCaml Stack data structure ?

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#189]
The OCaml [Stack](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Stack.html) data structure might be used instead of the home made `stack` type in `terms.ml`.  The ocaml Stack should be more efficient as operations are done in-place.

**Comment by rlepigre** [comment]
I am pretty sure it wouldn't be more efficient at all.

Note that we are effectively manipulating pointers all the time, so doing what you say typically amounts in using the type `term list ref` instead of `term list` for stacks. The overhead of a (useless) reference at the toplevel would be probably higher than passing an extra argument to the function.

**Comment by fblanqui** [comment]
Right.
