### ISSUE TITLE
What is the definition of HNF ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#206]
Is the code for hnf correct?

https://github.com/Deducteam/lambdapi/blob/82a9a7938d4f0e0a8f0c252f0021467d7b7de351/src/eval.ml#L205

**Comment by fblanqui** [comment]
```
let rec hnf : term -> term = fun t ->
  match whnf t with
  | Appl(t,u) -> Appl(hnf t, hnf u)
  | t -> t
```

**Comment by fblanqui** [comment]
It would be nice to add a comment on each possible strategy.

https://github.com/Deducteam/lambdapi/blob/82a9a7938d4f0e0a8f0c252f0021467d7b7de351/src/eval.ml#L211

**Comment by rlepigre** [comment]
What do you mean by "correct"?

**Comment by fblanqui** [comment]
I would like to see a definition of [w]hnf in the code in order to check whether this function is correct or not. This code looks strange to me. I remember we had a discussion about that on Dedukti but cannot find it again (this is not https://github.com/Deducteam/Dedukti/issues/113).

**Comment by GuillaumeGen** [comment]
Are you talking about https://github.com/Deducteam/Dedukti/pull/90 ?

**Comment by rlepigre** [comment]
In our implementation, the HNF is similar to SNF but it does not evaluate under binders. Basically, a HNF is any term `h t1 t2 ... tN` where `h` is a head (basically a variable, a symbol, or even a product, `TYPE`, `KIND` or a lambda if `N` is 0), and the `ti` are terms in HNF.

**Comment by rlepigre** [comment]
As I already explained, the definition of WHNF is exactly the one we would expect, with a small twist. It is possible that the argument are evaluated too much to exactly match the standard WHNF. This is justified in the implementation since we may need to evaluate arguments of a head symbol to check whether a rule may apply, and we are not going to throw away the work we did in the case where no rule apply. So really, the WHNF in our can really just be defined as some reduct of the usual WHNF. But this term obviously have the properties we expect of the WHNF: they allow us to check if a step can be taken in the evaluation machine. And since everything remains convertible there is also no problem for using our WHNF to test convertibility.

**Comment by fblanqui** [comment]
Thanks @GuillaumeGen for the link!

**Comment by fblanqui** [comment]
Rodolphe, there is no problem with whnf. My question is about hnf. For hnf, I would expect the following code instead:
```
let rec hnf : term -> term = fun t ->
  match unfold t with
  | Abst(a,t) ->
     let x,t = Bindlib.unbind t in
     let t = Bindlib.bind_var x (lift (hnf t)) in
     Bindlib.unbox (_Abst a t)
  | t         -> whnf t
```

**Comment by rlepigre** [comment]
For HNF I don't really know what we want. This evaluation function was implemented according to what was done in Dedukti if I remember well. For me it does not really make sense to evaluate under lambdas in this function, but I really don't know what we want to use it for so I might not have the right intuition. For now, it is only used for "debugging" purposes I guess, but I personally never used it. From my perspective only WHNF and SNF make sense. The former is used internally, so we may want to observe its behavior. And the latter gives the normal form of a term, which may be useful to display smaller terms and perform computation deeper in terms.

What you propose is to stop evaluating the arguments of the head (see my first message above), and evaluate under lambdas if they appear at the head (in which case there may not be any argument otherwise this would be a redex), thus doing both more evaluation and less evaluation at the same time.

**Comment by fblanqui** [comment]
@GuillaumeGen : does HNF still exist in Dedukti? It doesn't seem to appear in master. If so then we could simply remove it too.

**Comment by GuillaumeGen** [comment]
It has been removed from Dedukti 2.7

**Comment by rlepigre** [comment]
I'd juste remove it as well then.
