### ISSUE TITLE
Natural numbers builtin are not printed as such

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#209]
When defining the builtins "0" and "+1", we expect goals to be printed using natural numbers, at least for "0" which cannot be used as identifier. This is not the case currently.

**Comment by fblanqui** [comment]
This means that printing should depend on the signature, or at least the builtins.

**Comment by rlepigre** [comment]
No, not really. This particular example only concerns syntactic sugar like zero and successor. Other builtins do not suffer from the same problem, since they only give a "standard" name to some constructor. In their case, printing the actual constructor (not the builtin name) is the expected result.

For natural number literals, we could arguably recognize literals when the builtins are set. This would not be difficult to do.

**Comment by fblanqui** [comment]
Ok, but how to know that those builtins are set? By using some reference?

**Comment by rlepigre** [comment]
Good point, it is not completely trivial.
