### ISSUE TITLE
Why --gen-obj is not by default ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#212]

**Comment by rlepigre** [comment]
Most of the time we check independent files, so there is really no point in generating object files. And anyway, an object file does not have to exist, even in the case where there are dependencies, so there is really no point in making it the default. The only reason to use it is when you want do compile some things separately.

Anyway, all of that will change soon since we will need some way to compute dependencies separately to solve the issue raised by @ejgallego. And in the process, the option will probably disappear, and object file will always be produced.
