### ISSUE TITLE
Decision trees and empty pattern

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#236]
```
A : Type.

b : A.

h : A -> A -> A -> A.
i : A -> A -> A -> A -> A.

def f : A -> A -> A -> A -> A.
[] f b --> h.
[] f --> i.


#ASSERT f == i.
```
This file fails with decision trees and the `--keep-order-rules` because of the last rule with an empty pattern.

Do we want to allow the user to enter such rules?
If so, a simple fix would be to transform the last rule into
```
[x] f x --> i x.
```
or the code in  `dtree.ml` can be adapted, but it seems to be a nontrivial change.

**Comment by francoisthire** [comment]
What if the type of `f` is just `A`? Anyway, your file should be accepted. You cannot expect that `f` is applied.

**Comment by gabrielhdt** [comment]
You mean that you do a definition?  This is not handled by decision trees.  Ah indeed my 'fix' would require `f` to be always applied.

**Comment by francoisthire** [comment]
If `f` is an empty pattern, it can always be a definition. But in Dedukti a definition is translated as a rewrite rule. Hence unfolding definitions, what is called `delta` reduction is done by the same engine. It is not your case?

**Comment by gabrielhdt** [comment]
No, in `lambdapi` a symbol has a `sym_def : term option ref` field which contains the definition, so we don't use a rewrite rule.

**Comment by fblanqui** [comment]
Such a rule should be rejected indeed. The user should use a definition instead.

**Comment by gabrielhdt** [comment]
So I guess we should raise an error when we encounter a rule of arity 0

**Comment by fblanqui** [comment]
Yes, it would be better. What do you think @rlepigre ?

**Comment by francoisthire** [comment]
> Such a rule should be rejected indeed. The user should use a definition instead.

Are you sure ? Because the problem with definition is that it is not recursive. While with a rewrite rule, we can have recursive definitions. However, in the case of a recursive definition, are we sure that the pattern will never be empty?

```lambdapi
[] f --> C[f].
(; or ;)
[] f --> C[g].
[] g --> C[f].
```

Such thing cannot be achieved with a definition mechanism.

**Comment by fblanqui** [comment]
But this is not compatible with DK which has no notion of a definition :=, right? So, if we do this, then we need to translate such DK rule declaration into a LP definition.

**Comment by fblanqui** [comment]
Right François. But, then, your system does not terminate...

**Comment by rlepigre** [comment]
Indeed, we should reject empty lists of patterns early. I'll have a look at how to best fix that later, I am working on decision tree stuff right now.

**Comment by francoisthire** [comment]
> But this is not compatible with DK which has no notion of a definition :=, right?

Well, it has, but it seems more permissive.

> Right François. But, then, your system does not terminate...

Yes, but I tend to believe now that termination is to strong when we do encodings. What we want is something weaker which is when you are in the image of the translation, then the system terminates.

Moreover, I thought that you prefer a very permissive system and use external tools to check termination for example than ensuring such criterion syntactically.

**Comment by fblanqui** [comment]
Right but allowing f -> C[f] seems simply too much. Do you have any useful example?

**Comment by GuillaumeGen** [comment]
> Right François. But, then, your system does not terminate...

If `g` takes arguments in the second rule of François's example, we can probably craft terminating examples.

**Comment by fblanqui** [comment]
Thanks to craft such an example Guillaume. But, by "useful example" I mean something used in some encoding...

**Comment by GuillaumeGen** [comment]
It can simply be
```
[] f --> g.
[] g 0 --> 0.
[] g (s x) --> f x.
```
This example has of course no interest, but being impossible to write with `:=`.

**Comment by rlepigre** [comment]
If you really need that kind of example you can always modify it so that `f` takes on argument of type `unit`. In my opinion it is far better to encourage the use of definitions since they suffice in most cases, and there is a simple workaround for your examples (and similar ones).

**Comment by gabrielhdt** [comment]
`f \coloneq g` in lambdapi?

**Comment by francoisthire** [comment]
But again, I don't understand your policy. You allow rewrite rules which will never be used because the LHS is not typable but you refuse rewrite rules which might be useful someday... I understand there is a trade-off to have but as far as I know the argument "Give me a concrete example" does not work to allow rules where LHS are not typable (and definitively won't be).

**Comment by fblanqui** [comment]
Guillaume, your example can be written in LP as follows:
```
symbol g : ...
definition f := g
rule g 0 --> 0
and g (s x) --> f x
```

François, one reason is that LP is a proof assistant and not just a rewrite engine or a type-checker. One general principle is to possibly have only one construction for doing something. Here, for instance, to use
```
definition f := r
```
instead of
```
symbol f : T
rule f --> r
```
Note that, with definition, there is no need to give the type.
This makes the development more readable and, internally, this is more efficient as well.
So I think that the advantages outweigh the inconveniences.

As for untypable LHS, we try to do our best: a warning is output when we detect that a LHS is not typable. We could indeed turn this into an error. But we cannot do it in general as it is undecidable.

**Comment by gabrielhdt** [comment]
In fact my issue was more generic and happened when a rule was below another one with higher arity, and with the `--keep-rule-order` flag was set.
