### ISSUE TITLE
Allowed infix operators

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#253]
= is currently forbidden which is not nice. Perhaps because it is used in `let x = t in u`. But would it really create important grammatical conflicts to allow =? On the other hand, ≡ is not forbidden while it is also used in `assert t ≡ u`. So, I propose to allow both = and ≡.

**Comment by rlepigre** [comment]
That is a very bad idea, at least if we keep the syntax `let x = t in u`. However we could change the syntax of let-bindings so that it becomes `let x ≔ t in u`. In that case, allowing `=` as an infix would be fine. Should I make this change?

Good point for `assert t ≡ u`: infix `≡` should not be allowed due to this syntax. I'll have a look at the parser to see what I can do to fix that. Or we could just ignore the problem for now.

**Comment by rlepigre** [comment]
I think I told you already: I anticipated a possible `'a'` syntax (for characters).

For the syntax of assertions I don't know. Maybe `assert conv(t, u)`? That's not great.

**Comment by rlepigre** [comment]
Fixed by a74ac40c8079ac5c4b1878a9addc58374fcb6dfd.

**Comment by fblanqui** [comment]
You told me already perhaps, but it's better to write it in a comment as you can seen... ;-)

Why not `asserteq t, u` (and `assertnoteq t, u`)?

**Comment by rlepigre** [comment]
I don't like that we need yet another keyword for that. We can continue this discussion in #254.
