### ISSUE TITLE
Compare the domains ?

### ISSUE THREAD

**Issue by rlepigre** [Deducteam/lambdapi#3]
https://github.com/rlepigre/lambdapi/blob/f66fb0aac277713723752b908a7a722e91867f04/eval.ml#L239

**Comment by rlepigre** [comment]
Indeed not necessary (Dedukti ignores it). Removed.

**Comment by fblanqui** [comment]
It would be nice to add here, and in the code, a theoretical 
justification or a reference to a paper justifying this optimisation.


Le 25/01/2018 à 14:19, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
What would be a good reference for that? Is this a direct consequence of product compatibility?

**Comment by fblanqui** [comment]
The current comment seems wrong: "If the bodies are found to be 
convertible, then they must
     live in the same type (rewriting rules are well-typed).  This 
implies that
     the domains must be convertible." What if you compare \x:a.c and 
\x:b.c with a<>b? The bodies are the same but the annotations are not 
convertible. Perhaps this situation cannot happen because type 
annotations have already been checked (in typing.ml)? Anyway, this 
comment should be fixed and developed.


Le 26/01/2018 à 14:57, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
I'm not sure how to justify this actually, so I reverted to comparing the domains. It is probably possible to justify this optimisation since Dedukti uses it.

**Comment by craff** [comment]
On 18-01-31 07:20:58, Rodolphe Lepigre wrote:
> I'm not sure how to justify this actually, so I reverted to comparing the
> domains. It is probably possible to justify this optimisation since Dedukti
> uses it.

Salut,

Ah, un nouvel argument pour les preuves: puisqu'ils le font dans le code,
c'est que c'est correct. On devrait l'utiliser dans le papier toplas celui là.

;-)

A+
Christophe

**Comment by fblanqui** [comment]
As there is no new argument here, I propose to close this issue. @rlepigre what do you think?

**Comment by rlepigre** [comment]
@fblanqui: yes, we can close.
