### ISSUE TITLE
Bug in rule RHS type inference.

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#303]
Dear all, 

The following example ``test.dk`` typechecks with Deducteam/Dedukti@e6310f84
```
U : Type.
u : U.
f : (U -> U) -> Type.
def G : U -> Type.
H : U -> Type.
[v] G v --> a : H v -> f (b => u).
```
```bash
$ dkcheck test.dk 
[SUCCESS] File 'test.dk' was successfully checked.
```
while rule RHS type inference fails with lambdapi
```bash
$ lambdapi test.dk 
[test.dk, 6:26-27] Variable [b] could be replaced by [_].
[test.dk, 6:0-34] Uncaught exception [File "src/basics.ml", line 113, characters 36-42: Assertion failed].
```
At some point, Lambdapi is testing equality between metavariable ``v`` and "term environment" ``v`` and then fails.

**Comment by fblanqui** [comment]
I believe I see where is the problem (in sr.ml).

**Comment by fblanqui** [comment]
No, in fact, the problem is in https://github.com/Deducteam/lambdapi/blob/a0009fdaa53b607c53ebb8d1ee3a58b8d4bb8bc1/src/scope.ml#L281-L289

**Comment by fblanqui** [comment]
RHS metavariables may have types containing term environments (TEnv). When inferring the type of a RHS, we should replace these term environments by terms so that Basics.eq does not fail.

**Comment by rlepigre** [comment]
I'm not sure I understand what you are explaining here. One thing that I noticed is that if you replace the variable `a` by a wildcard then the problem disappears (and you can do that here because it is not bound). I'm not quite sure why this is the case though, I don't have time to investigate.

**Comment by Rehan-MALAK** [comment]
I came across this bug because in my experiments, ``a`` was bound.
Some more examples where the bug is absent (in lambdapi syntax this time).

```
constant symbol U : TYPE
constant symbol u : U
constant symbol v : U
constant symbol f : (U ⇒ U) ⇒ TYPE
symbol          G: U ⇒ TYPE
constant symbol H : U ⇒ TYPE
rule            G &v → H u ⇒ f (λ b, u)
rule            G &v → H &v ⇒ f (λ b, u)
rule            G &v → ∀ (_ : H u), f (λ b, u)
rule            G &v → ∀ (a : H u), f (λ b, u)
rule            G &v → ∀ (a : H &v), f (λ b, u)
```
Here, only the last one fails in Basics.eq

**Comment by fblanqui** [comment]
I know what's the problem. At scoping time, b is given a type ?0 a where ?0 : H &v ⇒ TYPE. Before calling infer, we need to replace &v by ?v. When you replace a by _, b cannot depend on a anymore, and is given the type ?0 with ?0 : TYPE, which is no problem. I will try to fix ASAP.

**Comment by fblanqui** [comment]
I'm afraid I won't have the time to fix this issue very soon. So @Rehan-MALAK , @gabrielhdt , thanks to try to fix it.

**Comment by gabrielhdt** [comment]
With the smaller and failing example
```
constant symbol U : TYPE
constant symbol u : U
constant symbol f : (U ⇒ U) ⇒ TYPE
symbol          G : U ⇒ TYPE
constant symbol H : U ⇒ TYPE
rule            G &v → ∀ (a : H &v), f (λ _, u)
```
logs say (`--debug ius`)
```
[infr] ?0 is of type [H &v ⇒ TYPE]
```
so it seems that `?0`, which is created when scoping the right-hand side, is given the aforementioned type, in `meta.meta_type`.

**Comment by rlepigre** [comment]
OK, so the problem is actually more subtle than I thought, but I finally understand it. It actually has nothing to do with SR checking, but with scoping. Following the example given by @gabrielhdt above, we are working with the rule:
```
rule G &v → ∀ (a : H &v), f (λ _, u)
```
The RHS has two occurrences of the term environment `&v`:
 - one is explicit, in the type of bound variable `a`,
 - the other is in the type of the unnamed bound variable in `(λ _, u)`. Indeed, with dependent types it may well be that the type of that variable depends on `a : H &v`, and so `&v` appears in the type of the meta-variable.

Now the problem is that this second occurrence is never properly bound in the RHS binder! The problem is that we have always considered metavariables to be closed objects. And this is indeed a very sane restriction to have. However, in a rule RHS (only), a metavariable can contain free term environment variables.

I'll work on a fix whenever I have time. That should not be too complicated, and should only involve modifying the way we generate metavariables in scoping. Indeed, the important thing is to create metavariables (and especially their type) in the `Bindlib.box` type in scoping, and never use "unboxed" terms (currently it is used though `Env.to_prod` for example). In particular, we should not use `_Meta` there since it only works on closed metavariables.

**Comment by rlepigre** [comment]
> RHS metavariables may have types containing term environments (TEnv). When inferring the type of a RHS, we should replace these term environments by terms so that Basics.eq does not fail.

We do replace them when checking SR! However as I explained above, we involuntarily create free term environment variables during scoping...
