### ISSUE TITLE
mapping modules and eglot

### ISSUE THREAD

**Issue by gabrielhdt** [Deducteam/lambdapi#325]
When using emacs, the eglot server exits abnormally with error code 1, and this rather informative message
```
Ill-formed argument to "--map": module path [demo] is already mapped.
```
It exits when I open a new file. It is also related to #319 for the `--map` option.

My `lambdapi.pkg` is
```
package_name = demo
root_path = demo
```
and the headers of my development files are
```
require open demo.lhol
```

**Comment by rlepigre** [comment]
I was somehow assuming that there would be one instance of the server running per file. That is not true according to what you are saying.

In any case, solving #319 will fix the "exit" issue.

**Comment by rlepigre** [comment]
I actually fixed this bug first, can you confirm that it is gone @gabrielhdt?

I'll take care of the other issue during the weekend probably.

**Comment by gabrielhdt** [comment]
Thanks! It is a lot better, *but*, I ran into
```
"Error when loading module [personoj.encodings.lhol].\nUncaught exception: [File \"src/core/files.ml\", line 219, characters 6-12: Assertion failed]"
```

**Comment by rlepigre** [comment]
Oh, I think I know the problem.

**Comment by rlepigre** [comment]
This should do the trick. Tell me if there is any other problem!

**Comment by fblanqui** [comment]
Why not doing a PR?

**Comment by rlepigre** [comment]
I probably should have, but since this was a pretty critical problem to use the LSP interface, and I am the only one that really seem to understand the code I modified, I though this would only be a waste of time. (Also, I knew CI would go through as it already ran on my fork, so `master` was never broken.) I will however open a PR when I address the documentation issue and possibly also certain limitations of the module and file management system, because this will need feedback.
