### ISSUE TITLE
Make (install) and lib/example directory

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#334]
Make and make install compiles and installs the files in lib/example. I would prefer to move this example files in tests/OK/.

**Comment by rlepigre** [comment]
The whole point of this example is to show how to install libraries. It made a lot more sense when it was a tiny standard library that you could have built on instead of having your own repository @fblanqui. Moving this to tests makes no sense, if you don't want it just delete it. The current examples are useless as tests (probably already covered).

**Comment by fblanqui** [comment]
Thanks to delete it then.

**Comment by fblanqui** [comment]
There is no lib/ directory anymore.
