### ISSUE TITLE
Syntax change proposal

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#347]
Hi. I propose the following syntax changes:
- replace \forall by \Pi to allow users to use \forall and clarify the fact that LP is a logical framework
- replace & by $ to allow users to use & which is very common (boolean or, conjunction). $ is already used in shells and makefiles, so many people will grasp its meaning very quickly.

**Comment by gabrielhdt** [comment]
If we replace the forall by the Pi, perhaps we should replace the implication arrow by a simple arrow, and find something else for the rewriting arrow.

**Comment by francoisthire** [comment]
I would go for:

\to (aka simple arrow) for non dependent product
\hookrightarrow for rewrite rules

I think that the simple arrow for rewrite rules is a bit confusing.

I agree with other changes of Frederic otherwise.

**Comment by fblanqui** [comment]
Yes, we have to pick in https://unicode-table.com/en/sets/arrow-symbols/ an arrow for rewrite rules which is easy to distinguish from → and ⇒. What about ᐅ or 🡆 ?

**Comment by francoisthire** [comment]
I like curving arrows such as ↝ or ⤳ . My preference is ↪ (\hookrightarrow in LaTeX or in Unicode : U+21AA).

**Comment by rlepigre** [comment]
Frankly I am not convinced than changing `∀` is gonna improve anything. It is not like the user is gonna be able to define a light-weight quantifier syntax out of the box. In any case, most proof systems I know use `∀` and not `Π` (even those based on type theory). This symbol is kind of ugly, and it is also a lot less meaningful outside of the type theory community.

For `&` we already had this discussion several times I think. My opinion is that the `$` symbol is ugly (much like `#`) because it is very "dense" (at least in most fonts). The `&` symbol does not stand out as much. (And I would rather not take too much inspiration in shell or PHP syntax.) And the only reason it is commonly used is because it is ASCII, so people have picked it because it was available. There is no reason to stick to it for boolean conjunction. After all, we should not be designing the syntax of our language around an old notation for a boolean operator. Moreover, using `$` would then mean that it cannot be used for the Haskell `$` notation, an someone will eventually gonna complain about that. And we are gonna go over this same discussion over and over again.

For arrows I have mixed feelings. I don't really care as much as for the first two proposals. One thing that we should keep in mind though is that exotic symbols such as those @fblanqui and @francoisthire proposed are not widely provided by fonts. Using them would really be asking for trouble. The one that I would prefer among those would be `↪`, but it does not render very well in a terminal. The others are even worse, they don't even render well in a browser.

Instead of arguing over syntax details, I think the focus should rather be on writing actual Lambdapi code. I'm pretty sure we don't even currently have more than a thousand lines of meaningful (i.e., non-test, non-generated) Lambdapi code. This is really not enough to have any kind of perspective over the current syntax. For that I think we need ten thousand at the very least.

**Comment by francoisthire** [comment]
`Frankly I am not convinced than changing ∀ is gonna improve anything. It is not like the user is gonna be able to define a light-weight quantifier syntax out of the box. In any case, most proof systems I know use ∀ and not Π (even those based on type theory). This symbol is kind of ugly, and it is also a lot less meaningful outside of the type theory community.`

Ok, but what do you propose for people which embed a logic? They have to find a new symbol for the usual `forall` connective. 

> For & we already had this discussion several times I think. My opinion is that the $ symbol is ugly (much like #) because it is very "dense" (at least in most fonts). The & symbol does not stand out as much. (And I would rather not take too much inspiration in shell or PHP syntax.) And the only reason it is commonly used is because it is ASCII, so people have picked it because it was available. There is no reason to stick to it for boolean conjunction. After all, we should not be designing the syntax of our language around an old notation for a boolean operator. Moreover, using $ would then mean that it cannot be used for the Haskell $ notation, an someone will eventually gonna complain about that. And we are gonna go over this same discussion over and over again.

But again, what do you propose for people who want to use `&` to define boolean `and` for example?

> For arrows I have mixed feelings. I don't really care as much as for the first two proposals. One thing that we should keep in mind though is that exotic symbols such as those @fblanqui and @francoisthire proposed are not widely provided by fonts. Using them would really be asking for trouble. The one that I would prefer among those would be ↪, but it does not render very well in a terminal. The others are even worse, they don't even render well in a browser.

I did not think about that. Today, I am struggling a bit to read rewrite rules with the current arrow.

> Instead of arguing over syntax details, I think the focus should rather be on writing actual Lambdapi code. I'm pretty sure we don't even currently have more than a thousand lines of meaningful (i.e., non-test, non-generated) Lambdapi code. This is really not enough to have any kind of perspective over the current syntax. For that I think we need ten thousand at the very least.

True, but we need to find a solution for this I think. My position would be to have a modular syntax and offer a way to redefine these symbols so that the user can have its own preferences. I know you strongly refused this choice, but it could help with the adoption of the tool I think.

**Comment by francoisthire** [comment]
Another possibility would be to use editors' mode to handle this. For example the editor could print things differently depending on the configuration of the user.

**Comment by rlepigre** [comment]
> Ok, but what do you propose for people which embed a logic? They have to find a new symbol for the usual forall connective.

Yeah, obviously. But it should be possible to allow notations like `∀*` (i.e., combined with another symbol, or with a subscript/superscript).  

> But again, what do you propose for people who want to use `&` to define boolean `and` for example?

I don't propose anything. It is like asking "what if people want to use `fun` as a variable name in OCaml?". You just can't, deal with it. Use `fun_` or whatever.

> True, but we need to find a solution for this I think. My position would be to have a modular syntax and offer a way to redefine these symbols so that the user can have its own preferences. I know you strongly refused this choice, but it could help with the adoption of the tool I think.

Nah, that is not reasonable. We do not want to maintain several version of the syntax! We already have no users, how would it be a good thing if everyone would work in a different syntax? The typical way to learn a language is to copy paste stuff form other people's source files and modify them. If we had several incompatible syntaxes then doing that would be just impossible.

What everyone has to realise is that with parsing you can't have your cake and eat it too. There will necessarily be limitations! And people don't just "adopt" languages. There is literally no one that is currently thinking "oh I'm not gonna use Lambdpi because its syntax does not allow `&` as an infix operator". However, not having examples of non-trivial developments is a problem if external people were to look at Lambdapi.

**Comment by fblanqui** [comment]
Hi Rodolphe.

I repeat: LP is not a logical system in itself; it is a logical framework. In this context, it is important to clearly distinguish the logical level from the metalogical level, and let users use \forall. In Isabelle, which is a logical framework too, the metalogical universal quantification is written /\ if I remember well. Isabelle is based on simple type theory. LP is based on dependent type theory. So this is quite natural to use \Pi. This is the most common notation for the dependent product currently I think.

As for &, it is used for centuries to denote conjunction, an infix operator. See https://en.wikipedia.org/wiki/Ampersand. So it is not a good idea at all to use it for pattern variables as a prefix operator. $ has the advantage of not being used in logical or mathematical notations, and it is used as a prefix in common language.

As for developments in LP, you are a little bit wrong. Between Bruno, Rehan, Gabriel, Amélie, myself and perhaps others, we have at least 5,000 lines of hand-written code. That's not a lot of course, but that's more than what you think. To go further, we need to add more tactics.

Anyway, as you said, LP has very few users currently. So it is very easy to change the syntax now, and do experiments. So, I will do a PR with those changes.

**Comment by rlepigre** [comment]
OK, but then there is no use changing the syntax if there is no deeper integration of the universal quantifier. We at least want to have the syntax `∀ <args>, <term>` configured with a builtin symbol and converted at parse time to `forall (λ <args>, <term>)` or whatever it needs to be. If we don't have that kind of thing at the same time, I don't see what is the point here. In any case, the design of such feature needs discussion. What logical symbols do we support for the embedded logic? What similar special syntax do we need? Thanks to come up with a detailed plan if that is the way you want to go.

If there are so many developments available, why is it that we get almost no feedback? These developments should certainly be tested by our CI otherwise they are likely to break. They would be interesting to have as tests anyway.

**Comment by fblanqui** [comment]
I hope that the move to pacomb will allow users to define notations like in Coq or Agda. For instance defining \forall x:a,p as being \forall a (\lambda x:\tau a,p).

**Comment by rlepigre** [comment]
Well, it is not gonna magically allow you to do that. Someone needs to implement this. And this is not Pacomb-specific, this could be done with Earley as well.

**Comment by fblanqui** [comment]
See #354

**Comment by francoisthire** [comment]
Don't you think it would be possible to use the editor as a way for each user to use its own preferences? My point is that if the user is keen on having a `∀` symbol and it can't because it is reserved, maybe the editor could lied a little bit and print this symbol even if the real file uses `∀*` instead for example.

**Comment by rlepigre** [comment]
That is kind of what company-coq does to some extend, but I think this is quite orthogonal to the syntax of the language. Of course, users are free to do whatever they want with their editors.

**Comment by francoisthire** [comment]
> That is kind of what company-coq does to some extend, but I think this is quite orthogonal to the syntax of the language. Of course, users are free to do whatever they want with their editors.

But now this mode is used by many people which program in Coq on Emacs. The thing is the current project already have an editor mode for `emacs` so it would be easier it would be developped by the Lambdapi developpers. 

My point is that to use a tool as a `logical framework`, I think we need to deal with the numerous preferences of each potential user and if there is already something that allows the user to use his favorite symbols, I think that it would help with the adoption of the tool. However, I understand your point and this is why I am trying to suggest ideas which would lead to a good trade-off between something easy to maintain and something easy to use/modify.

Another idea would be to have a plugin mechanism for `lambdapi` so that you can change the user syntax. 

While I see that you are not completely against to change the syntax, you do not appeared to be convinced that this is important. But don't you think we can come up with a solution that would circumvent the problem that each user has its own preferred syntax. @fblanqui already mentioned the solution offered by `Isaballe`.

**Comment by rlepigre** [comment]
Indeed, I am really not convinced that the changes discussed here are important. At least not right now. There are far more important problems to solve for usability than these syntax details. Before going into that I'd like to see example being developed (in the repository, where I still think the standard library should be) where we have FIXME tags identifying elements of syntax (or anything else) that are not ideal. It is not a problem if syntax is not perfect the first time, but we can't just change it every now and then. Our syntax is already pretty good, it is not like if it was a complete no go. Yes it can be improved, but there need to be a clear reason. And a good reason would be to make libraries look better. But for that I always come back to the same thing: we need a library. In the repository.

**Comment by francoisthire** [comment]
> Our syntax is already pretty good, it is not like if it was a complete no go. Yes it can be improved, but there need to be a clear reason. And a good reason would be to make libraries look better. But for that I always come back to the same thing: we need a library. In the repository.

Ok, you are right, but I think there are two kind of potential users of `Lambdapi`:
1. Current users of Dedukti, meaning people which generates proofs from one system into `Dedukti` or `Lambdapi`. `Lambdapi` is already a target for that (PVS, Isabelle, Why3, SMTCoq with the work of Quentin Garchery and Chantal Keller if I am not mistaken). In the next few months there might be more proofs such as Coq or Matita, and beyond with the current Logipedia project
2. Users which aims to develop proofs in som ad-hoc weird logic. Currently I think there are less users but still a few such as interns in Deducteam or Bruno for Cubical Type Theory

My arguments are for people in the first group. I have the impression that yours are for people in the second group, am I right? Because people in the first group do not need a standard library since it will already exist in the system they will import. 

Again, I am just making suggestions, in particular as future user of `Lambdapi` in the first group I mentioned.

**Comment by rlepigre** [comment]
I guess that both groups of users you mention have roughly the same needs, at least if people that generate Lambdapi code care about its readability. If they just want to generate and don't care about the result then they could as well generate a more compact binary format. So basically, the thing everyone seems to want is a way to hide the meta-level, or said otherwise, to have a lighter syntax to work in an encoded logic. This makes sense, and we can work on that. But we need to figure out what the problem exactly is first. That is, we need to have examples of such things in the current syntax, and also examples of what syntax we would like to have instead.

**Comment by rlepigre** [comment]
Changes done in ba050de6795087ebf6fd72b89639603b17060c33 (#356, previous #354)
