### ISSUE TITLE
Non-dependent product not printed as such

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#358]
https://github.com/Deducteam/lambdapi/issues/357#issuecomment-615150233

**Comment by rlepigre** [comment]
Here is a minimal example to reproduce.
```
symbol A : TYPE
symbol f : A → A → A
type f
type λx y, f x y
```

**Comment by rlepigre** [comment]
Note that the fix disables an optimisation. It is usually possible to stop lifting at binders that are marked as closed (this is metadata carried by the `('a, 'b) Bindlib.binder` type), however since we use references for instantiation this metadata can become wrong after a while, and so it is important that the `Terms.lift` function also updates it (it is used, e.g., for printing).

It would seem that disabling the optimisation does not reduce the global performances too significantly. If that becomes a problem later then we can try to be smarter. For now I think it is better to remove the optimisation.
