### ISSUE TITLE
Emacs LSP mode with goals display is freezing with new files

### ISSUE THREAD

**Issue by Rehan-MALAK** [Deducteam/lambdapi#432]
Hi !

If I do 

```bash
echo "constant symbol A : TYPE" > tests/OK/new.lp
```

then I open emacs with the usual ``.emacs`` configuration

```emacs
(require 'opam-user-setup "~/.emacs.d/opam-user-setup.el")
(load "lambdapi-site-file")
```

I can open emacs in lambdapi lsp mode with the goals window

```bash
emacs tests/OK/new.lp
```
and do some lambdapi development.

But if I start a new file 

```bash
emacs tests/OK/new2.lp
```
emacs freezes when I try to type

```lambdapi
constant symbol A : TYPE
```
and in fact anything followed by ``<Enter>``

Can you reproduce this ?

This may be related to #348

**Comment by fblanqui** [comment]
Yes, I have the same problem by just launching emacs with a non-existing filename and writes `symbol A:TYPE`. @vycastor do you have any idea what could be the problem? Could you please fix it?

**Comment by vycastor** [comment]
Looking at it!

**Comment by vycastor** [comment]
Looking at the log, it seems that because the file does not exist on the FS, it cannot find it, then backtraces.

`[[BT]]: Raised at file "hashtbl.ml", line 194, characters 13-28`
`Called from file "src/lsp/lp_lsp.ml", line 226, characters 12-44`
`Called from file "src/lsp/lp_lsp.ml", line 401, characters 6-44`

I'll try to fix it asap. I do not know if it is related to #348.

**Comment by vycastor** [comment]
This issue doesn't seem to be especially related with proof/goals, it happens even when I deactivate the related hooks in lambdapi-mode.el. The only simple user-side way to circumvent this issue is to `touch <file>` before editing with emacs.

Nevertheless, I'll be trying to find a solution that encompasses the whole scope of the issue (in fact, it seems that many LSP calls only work with existing files). Maybe we can force emacs to create the file on opening if it doesn't exist? It would be the easiest workaround.

**Comment by Rehan-MALAK** [comment]
I don't know when and how this bug has been resolved but the current behavior of master is :

- if I open emacs with a *.lp file which doesn't exist... then eglot doesn't seem running
- if I open emacs with a *.lp file which already exist... then eglot is working correctly

so I think we can close it ? can somebody confirm ?

**Comment by fblanqui** [comment]
I still have a problem. When I open a new file, write something, every works. But, then, when I do Ctrl-C Ctrl-N, it loops.

**Comment by ejgallego** [comment]
@fblanqui can you post the log?

**Comment by fblanqui** [comment]
How do I get it @ejgallego ?

**Comment by ejgallego** [comment]
As of latest version it is supposed to be in `let default_log_file : string = "/tmp/lambdapi_lsp_log.txt"`

**Comment by fblanqui** [comment]
Find it here attached:
[lambdapi_lsp_log.txt](https://github.com/Deducteam/lambdapi/files/5523034/lambdapi_lsp_log.txt)

**Comment by fblanqui** [comment]
It seems to loop by repeating the following:
```
[read]: {
          "jsonrpc": "2.0",
          "id": 6,
          "method": "textDocument/hover",
          "params": {
            "textDocument": {
              "uri": "file:///home/blanqui/src/lambdapi/tmp/a.lp"
            },
            "position": { "line": 1, "character": 0 }
          }
        }
[[BT]]: Raised at file "hashtbl.ml", line 194, characters 13-28
Called from file "src/lsp/lp_lsp.ml", line 107, characters 38-67
Called from file "src/lsp/lp_lsp.ml", line 267, characters 18-33
Called from file "src/lsp/lp_lsp.ml", line 405, characters 6-44
```
But the file doesn't exist.

**Comment by ejgallego** [comment]
Thanks @fblanqui , working on a fix.
