### ISSUE TITLE
Change organization of source files ?

### ISSUE THREAD

**Issue by amelieled** [Deducteam/lambdapi#487]
It's probably the good time to change the file system hierarchy in order to increase the readability of this github (and the modularity too).

**Comment by fblanqui** [comment]
Why?

**Comment by amelieled** [comment]
"to increase the readability of this github (and the modularity too)."

**Comment by fblanqui** [comment]
I don't think that this is currently an issue and that this is very urgent to do that.

**Comment by amelieled** [comment]
Why do you close it even if it's not urgent?

**Comment by amelieled** [comment]
In fact, it is, and to be honest with you, I discussed this morning with @gabrielhdt and @EmilieGrienenberger about that, so it's not completely my idea.

**Comment by amelieled** [comment]
Moreover, it's a discussion, or a proposition.

**Comment by fblanqui** [comment]
Then, it would be good to provide arguments for such a change now.

**Comment by gabrielhdt** [comment]
In my opinion, such a reorganistion may indeed not be urgent when we consider lambdapi as a command line prover, or a proof checker tied to a LSP server.

However, in the team we are more and more using lambdapi as library, may it be to implement a coercion insertion algorithm in my case, to port DkMeta to Lambdapi; or, in the near future, to port Universo to Lambdapi. When we lambdapi as a library, we become heavily depenent on what the code OCaml code exposes, and the datatypes. The current lack of specification has a quite annoying consequence on the code of these tools since any part of lambdapi may change anytime. There have already been examples of such tools becoming broken because of such modifications.

Even regarding lambdapi code, it may help in the future because dependencies are getting blurred, and non obvious. For instance, the flow of a file is to be parsed, using code of `syntax.ml`, then to be scoped with `scope.ml` to terms of `terms.ml`. Therefore, I think (maybe it's only me) that intuitively, we would expect `terms.ml` to perhaps depend on `syntax.ml`. But actually it's the opposite. And it may be the case that not having clear interfaces increases the entanglement of modules.

As is said in [The Art of Unix Programming](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html#id2877537),
> The only way to write complex software that won't fall on its face is to hold its global complexity down — to build it out of simple parts connected by well-defined interfaces, so that most problems are local and you can have some hope of upgrading a part without breaking the whole.

More information can be found in [Chapter 4](http://www.catb.org/~esr/writings/taoup/html/modularitychapter.html), for the curious.

On the other hand, I agree that such a change is not benign, so we should not rush, and do it all at once. But I beilieve that we can incrementally clarify the behaviour of several parts of the code, without requiring too much work; provided that we discuss the role of each part, and agree on clear and easy to understand interfaces.

**Comment by ejgallego** [comment]
I feel that reorganizing code is indeed a natural process and IMHO a low barrier to refactoring tends to outweigh in terms of benefits the problems that code-churn introduce. If you folks working in the codebase would like to try and structure things in a way that fits your vision better I'd say go ahead. 

And don't have fear to keep refining or even backtracking on some choices. We have plenty of examples where this kind of code reorganization happens often [for example Isabelle] and it is IMO a success. That's also one of the goals of build systems like Dune, to provide good and cheap support for moving code around, defining libraries etc... Dune itself tends to have large refactorings often as the role / separation of components change.

A problem in the OCaml world is style, there are several styles on how to organize things and indeed that's a quite open matter, with several preferred styles and no clear winner. For example, I program very differently now than 2 years ago, mostly influenced by the style I've seen in other projects, but each style has strong and weak points.

**Comment by amelieled** [comment]
And why now?:
It's just because you have recently merged complex PRs like [WIP] Mutually defined inductive types (#445) and [WIP] proof mode with typing/unification goals and a solve tactic (#422).
So now, there are almost only PRs about "IDE" (like VSCode): 
  - fix #393: small changes?
  - Added click to focus feature: ~IDE
  - add example with focus and adapt emacs mode: ~IDE
  - [WIP] New parser: independent changes
  - [POC] run Elpi code in lambdapi: deprecated? (new way?)
  - [pure] [lsp] Try to recover unit testing of pure interface: ~IDE
  - depgraph.sh generates the dependency graph of the project (#154): independent (and small?) changes
  - [WIP] Switch from Earley to Pacomb: deprecated?
  - Implementation of an algorithm for checking subject reduction: deprecated?

**Comment by gabrielhdt** [comment]
I'm not sure there is really a "good time", provided that the changes are clear and made step by step. IMO any one may at any time propose some reorganisation, because the changes involved are conceptually easy to understand (no "complex" coding involved).

And concerning the new parser, the code is not that independent, it messes slightly with the syntax.

**Comment by fblanqui** [comment]
I fully agree with Emilio and Gabriel. There is no problem in restructuring the file structure if necessary but this must be done step by step whenever it is really necessary and not in one shot and a priori without clear and strong reasons.
Now, we should perhaps do this kind of discussions in the "Discussions" tab https://github.com/Deducteam/lambdapi/discussions now offered by Github and reserve issues for real problems.

**Comment by EmilieGrienenberger** [comment]
A reason to start discussing and try new structures right now is the fact that, as Gabriel mentioned, we are currently trying to port tools from Dedukti 2.7 to Dedukti 3. A number of tools depend/will hopefully soon depend on lambdapi and use it as a library. A restructuring clarifying the dependencies, status, and interfaces of files would be very helpful to program and maintain these tools. I would even say that the structure is already an issue for our development projects (a minor one for the moment). But as they evolve it will inevitably become a bigger one. The goal is to try to anticipate these issues, and that is why the discussion opened by Amélie and her proposition of a gradual timeline seem very relevant to me.

**Comment by fblanqui** [comment]
I understand. But, as said, I would prefer to first understand what is needed for each tool and why. So, first, thanks to give more details about who is trying to do what.

**Comment by amelieled** [comment]
Yes, so please, just be patient :)

**Comment by fblanqui** [comment]
As already mentioned, https://github.com/Deducteam/lambdapi/issues is reserved for real issues. For questions or discussions, please use https://github.com/Deducteam/lambdapi/discussions. I therefore close this "issue".

**Comment by amelieled** [comment]
It's an issue (See above), and not really a "simple" discussion.
The previous timeline shows you that we need to do several PRs, the first one is #492 , and we are waiting for your point of view.
We should discuss on each PR, but not really here.

**Comment by amelieled** [comment]
But where is my timeline?? It's wonderful if everyone can do some changes in the message of each other!
How this is possible?
