### ISSUE TITLE
Emacs Lambdapi mode smie error

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#592]
After installing the Lambdapi mode for emacs, I get the following warning message when opening Lambdapi files (for example `tests/OK/244.lp` or `tests/OK/61.dk`): 

`Warning (smie): token [ is both opener and neither`

I assume this is linked to the `lambdapi-smie.el` file, do you know where this comes from exactly and how to fix it ? This stops emacs from loading the Lambdapi mode.

**Comment by gabrielhdt** [comment]
Indeed it comes from `lambapi-smie.el`. I'm surprised that it stops emacs from loading lambdapi, since it's only a warning. To fix this, we should take a fresh look on the grammar of the indentation engine: this message says that token `[` is used as the opener of a rule, and in the middle of another one, whereas emacs likes to identify tokens that are always at the start of rules (openers), tokens that are always at the end of rules (closers),  or tokens that are in the middle of rules (neither).

I think we should simplify a lot the grammar of the indentation engine, the goal is not to reflect precisely the grammar of the language (the parser generator of emacs isn't able to do that anyway).

For more information, you may refer to [Emacs documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/SMIE.html#SMIE).

**Comment by QGarchery** [comment]
Ok, thanks for the insight. To be more precise: I don't know what stops emacs from loading lambdapi, but this is the message I get

**Comment by gabrielhdt** [comment]
You may want to open the file `lambdapi-smie.el` in emacs, and use `M-x eval-buffer`, to see what it says.

**Comment by QGarchery** [comment]
I get the same warning : `Warning (smie): token [ is both opener and neither`

**Comment by QGarchery** [comment]
I found why it could not load the lambdapi mode: it seems that the warning message was blocking the message telling me that it depends on emacs package `math-symbol-lists`. After installing it, the lambdapi mode loads as expected. Maybe it would help if `make install_emacs` printed a message like the following: 
```bash
Add the following lines to ~/.emacs (if not already done):
(require 'math-symbol-lists)
...
(require 'last-package-required)
(load "lambdapi-site-file")
```

**Comment by gabrielhdt** [comment]
Ah allright, thanks for the analysis. This is kind of inconvenient, and for this I recommend to install the mode through Melpa, which handles dependencies.

**Comment by fblanqui** [comment]
This is indeed mentioned in the user manual. So, I close this issue.
