### ISSUE TITLE
The assume tactic does too much reduction

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#693]
Very recent commits (last few days) seem to change how rewriting is handled. This cause various issues, but I believe they come from the same one. I think it is because some rewriting is done at some unexpected place (see `test_assume` below).

```
require open Stdlib.Set Stdlib.Prop Stdlib.Eq Stdlib.FOL Stdlib.Nat;

symbol fold_arrow {p1 p2 : Prop} : π (p1 ⇒ p2) → π p1 → π p2
≔ λ p1_p2 p1, p1_p2 p1;

symbol test_assume (a b : ℕ) f : π (a = b ⇒ f a ⇒ f b)
≔ begin
  assume a b f;

  assume eab;
  // assume rewrites π (f a ⇒ f b) into π (f a) → π (f b)

  // This should fix the issue but does nothing instead:
  // refine fold_arrow _;

  rewrite eab;
  // Goal is not of the correct form, how to fix ?

end;


symbol test_rew_lambda f : π (`∀ a, `∀ b, f (a + b) ⇒ f b)
≔ begin
  // Does not rewrite under binders
  rewrite add_com;
end;

// Following declaration does not type check
symbol test_type_check (a b : ℕ) f : π (f (a + b) ⇒ f (a + b));
```

**Comment by fblanqui** [comment]
Thanks @QGarchery for your issues. These issues are not related and should be in separate issues but that's fine.

Issue 1 has been introduced in #681. Before, unification was in two steps: by first trying to unify without normalizing wrt user-defined rules and, in case of failure, trying to unify by normalizing wrt user-defined rules, to avoid normalization whenever possible. In #681, I removed the first step for simplifying the code. Unfortunately, our tests did not cover this case. I am going to revert this change.

Issue 2. You first need to do `assume f`. But, then this fails with `No subterm of [`∀ a, `∀ b, f (a + b) ⇒ f b] matches [x + y]`. Indeed, it is currently not possible to rewrite under binders. The PR #691 allowed to rewrite a closed term inside a binder. Here it is about rewriting a term containing bound variables. This requires some investigation. This issue may not be solved soon.

Issue 3. By default, the system assumes that implicit types are dependent. Hence, f gets the type `Π y:?1[a;b], ?2[a;b;y]` and, for the symbol type to be well typed, we need to solve the following constraint:
```
[...] Cannot solve ?2[a;b;b + a] ≡ Prop.
```
The system doesn't know how to solve a constraint of the form `?2[t1;t2;t3] ≡ Prop` when t1, t2 and t3 are not distinct variables. Indeed, in this case, modulo conversion of user-defined symbols, you could imagine other solutions than the constant function.
Here, there is no other solution than helping the system, and give him the type of f.

**Comment by QGarchery** [comment]
Thank you for the detailed explanations and also sorry for putting multiple issues into one.

For issue 2:  I read the changes too fast, and I understand why this is a more complicated issue (or feature wish) than I thought.

Issue 3 also makes sense now, thanks.

**Comment by fblanqui** [comment]
I moved issue 2 in #694 .

**Comment by QGarchery** [comment]
This is great, thanks. I reopen this issue because some reduction is still performed if the arrow is defined instead of declared.
In the example [assume.txt](https://github.com/Deducteam/lambdapi/files/6561398/assume.txt), the arrow `=>` is defined in such a way that it is rewritten into the lambdapi arrow. In this case the call to `assume` performs some reduction on the assumed hypothesis. If the arrow is instead declared (comment/uncomment lines 14-20), no reduction is performed on the assumed hypothesis. 
This is a minimal example so this seems like a minor reduction, but in my case, the reduction of an hypothesis as simple as `x < y` is 4 lines long. This is because I have everything defined (`<` is defined in term of a `compare` function, in turn defined by calling 2 match functions, ...)

I believe this issue to be more general than just for assume. I have another example where we can't rewrite at all when the equality is defined instead of declared. Should I post it here or on a separate issue?

**Comment by fblanqui** [comment]
Thanks to post your other example as well. We'll see if another issue needs to be open.

**Comment by fblanqui** [comment]
Hi @QGarchery . I do not see what is the problem in your example assume.lp. Without changing your file, after assume I get the following goal:
```
b: bool
H: π (is_true b)
-------------------------
?111: π ⊤
```
Could you please give me more details on what you get and what you expect to get?

**Comment by QGarchery** [comment]
Hi Frédéric, I'm expecting to get what you have, but instead `H` is reduced:
```
b: bool
H: π (if ⊤ ⊥ b)
--------------------
?27: π ⊤
```
I don't understand what's happening, I'm working with the latest lambdapi commit: 48fad58fba3f68e8b37b2d7f16fc60285962b02c

**Comment by fblanqui** [comment]
Ah right. Sorry I didn't use the right version.

**Comment by QGarchery** [comment]
Here is an example where rewriting fails when the equality is defined instead of declared: [rewrite_test.txt](https://github.com/Deducteam/lambdapi/files/6570991/rewrite_test.txt)

**Comment by fblanqui** [comment]
Remark: one workaround is to declare = as opaque, if you do not need to unfold its definition later.

**Comment by fblanqui** [comment]
The problem with the rewrite tactic is of a different nature. So I moved it to a new issue. A fix will come soon.

**Comment by fblanqui** [comment]
@gabrielhdt The problem we have here (in file assume.lp above) is that whnf introduces TRef's for sharing reductions in arguments which are not removed afterwise. Hence terms get cluttered with TRef's. Uncomment the following line to see this:
https://github.com/Deducteam/lambdapi/blob/b4043c0acbfd5e900aa8c055b65ec3ee55849a4d/src/core/print.ml#L274
And later calls to eq_modulo may reduce those TRef's because:
https://github.com/Deducteam/lambdapi/blob/b4043c0acbfd5e900aa8c055b65ec3ee55849a4d/src/core/eval.ml#L299-L308
whnf makes no difference between TRef's introduced in the current call and introduced in previous calls.
We could record TRef's created in the current call and reduce only those.
Note that https://github.com/rlepigre/ocaml-timed/blob/master/timed.mli provides neither the time of a ref nor a comparison function on times.
However, for the moment, I will try to modify eq_modulo so that it calls whnf only if the arguments are not syntactically equal.

**Comment by fblanqui** [comment]
I thought I could solve the current issue by modifying eq_modulo but this cannot work.
As you can see in the logs:
```
    4. check H : (π &(is_true b))
     5. infer H
     5. ?3[b]
?3[b] ≟ (π &(is_true b))
failed
    4. add ?3[b] ≡ (π &(((if ⊤) ⊥) b))
```
At some point, we need to check that H, which is of type `?3[b]` is also of type `π &(is_true b)`. & represents a TRef. Since we add a new constraint only if two terms are not equivalent, we call eq_modulo on those two terms, and `&(is_true b)` gets replaced by `&(((if ⊤) ⊥) b)`.  `π &(is_true b)` needs to be reduced since we do not know that it cannot reduce to a metavariable.

**Comment by fblanqui** [comment]
This seems to be exactly what we need. Thank you @gabrielhdt !

**Comment by QGarchery** [comment]
Works great for my case, thanks a lot !
