### ISSUE TITLE
rewrite tactic: equality not found in the equation

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#700]
See https://github.com/Deducteam/lambdapi/issues/693#issuecomment-851541090.

**Comment by QGarchery** [comment]
Thank you for the fix ! 

The problem seems to still stand if some reduction is needed beforehand to put the hypothesis in the right form.
Here is an example (using the same preamble to define the equality) showing this for both the `rewrite` tactic and the `reflexivity` tactic: [test_rewrite_reflexivity.txt](https://github.com/Deducteam/lambdapi/files/6589925/test_rewrite_reflexivity.txt)

**Comment by QGarchery** [comment]
Maybe this issue should be reopened since the `rewrite_test` provided in the `test_rewrite_reflexivity.txt` file does not work?

**Comment by fblanqui** [comment]
It works for me. Which version of LP are you using?

**Comment by QGarchery** [comment]
I'm using the latest version, commit bad5775c076124ca871fae0569f3993828d371ca (funny commit hash ^^)
The workaround is still fine, but uncommenting line 52 fails with:
```Expected = _ _ but found w (f w).```

**Comment by QGarchery** [comment]
Just tested it, works great, thanks !
