### ISSUE TITLE
Problem with normalisation when dealing with AC symbols

### ISSUE THREAD

**Issue by Thiagofelis** [Deducteam/lambdapi#712]
On the file [here](https://github.com/Deducteam/lambdapi/files/6715887/suc-alg.zip), upon calling compute on the term `λ x y, ((S (S (⋄ x))) ∪ (S (⋄ y))) ∪ Z` we get `λ x y, s 1 y ⊕ (s 2 x ⊕ (s 0 z ⊕ s 2 z))`, which is not in normal form, as the rule `s $p $x ⊕ s $q $x ↪ s ($p ⊕ₙ $q) $x` should apply. Indeed, when calling compute on `λ x y, s 1 y ⊕ (s 2 x ⊕ (s 0 z ⊕ s 2 z))` we get `λ x y, s 1 y ⊕ (s 2 x ⊕ s 2 z)`, showing that the previous term was not in normal form. My version of Lambdapi is `56f808ed`.

**Comment by fblanqui** [comment]
Hi @Thiagofelis . Instead of using zip files, thanks to use txt files: add myfile.txt instead of myfile.lp, especially if you have only one file. It generates less file manipulations.

**Comment by gabrielhdt** [comment]
You may use github's gists as well with `gist.github.com`, it's like using pastebin-like services. For instance, <https://gist.github.com/gabrielhdt/6004fb25049eb92f0eb486ea05b5d445>

**Comment by fblanqui** [comment]
@Thiagofelis Thanks to check #716.

**Comment by Thiagofelis** [comment]
Thanks for the fix, but unfortunately the problem seems to continue with other files: https://gist.github.com/Thiagofelis/f6172054f45121a63a03411dbbbddefe

**Comment by fblanqui** [comment]
@Thiagofelis The last commit seems to fix the problem. Thanks to check it on more examples.

**Comment by Thiagofelis** [comment]
This solves almost all of my problems, however I'm still able to find some few problems like this one https://gist.github.com/Thiagofelis/2a2eca3cdf6033ec312a63d39083b8ab

**Comment by fblanqui** [comment]
#723 fixed a number of problems in unification.
Now, the final type command succeeds.
The only remaining problem is that `type λ a b, head a b (tail a b)` does not succeed because:
```
Cannot solve s ((1 + 0) ⊕ₙ (1 + 0)) b ⊕ (s (1 + 0) a ⊕ (s (0 ⊕ₙ ((1 + 0) ⊕ₙ (1 + (0 ⊕ₙ (0 ⊕ₙ 0))))) z ⊕ s 0 ?7[a;b])) ≡ s 1 b ⊕ (s 1 a ⊕ s (0 ⊕ₙ (1 ⊕ₙ 1)) z).
Cannot solve s 0 z ⊕ s 0 ?7[a;b] ≡ s 0 a ⊕ s 0 z.
```
This is not surprising.
head is of type Π a: L, Π b: L, (El (V (set (s 0 (a ⊕ z)))) → U (set (s 0 z ⊕ (s 1 (b ⊕ z) ⊕ s 1 (a ⊕ z))))) → ...
tail is of type Π l: L, Π a: L, Π b: L, U (set (s 0 (l ⊕ z))) → U (set (s 1 b ⊕ (s 1 a ⊕ (s 0 l ⊕ s 1 z))))
The last constraint is not solved because ⊕ is associative and commutative, and defined by rules.
This can however be easily fixed by the user by indicating that the implicit argument l is in fact a:
`type λ a b, head a b (@tail a a b);` works well.

**Comment by fblanqui** [comment]
Find the last version of the test file here.
[Agda__Builtin__Sigma.txt](https://github.com/Deducteam/lambdapi/files/6839897/Agda__Builtin__Sigma.txt)

**Comment by fblanqui** [comment]
The previously mentioned problem is not related to normalization but to unification, and won't be fixed because it is too complex to be solved by a unification algorithm. So I will merge #716 and close this issue, unless you have other counterexamples related to normalization.
