### ISSUE TITLE
Unification rules are not saved to lpo files

### ISSUE THREAD

**Issue by dwarfmaster** [Deducteam/lambdapi#718]
When importing a file that contains a `unif_rule`, this rule is only used if the file is loaded directly and not from an lpo file.

Here is a minimal example. Assume you have a file `Defs.lp` that contain :
```lambdapi
symbol T : TYPE;
symbol t : T;
symbol u : T;
symbol F : T → TYPE;
symbol a : F t;

unif_rule F $t1 ≡ F $t2 ↪ [ $t1 ≡ $t2 ];
```

And a file `Usage.lp` that contains: 
```lambdapi

require open Unif.Defs;

symbol f {x : T} : F x → T;
symbol g : T ≔ f a;
```

`lambdapi check Usage.lp` succeeds if there is no lpo file for `Defs.lp`, but `lambdapi check --gen-obj Defs.lp; lambdapi check Usage.lp` results in the error : 
```
Loading ".../Unif/Usage.lp" ...
[.../Unif/Usage.lp:5:0-19] Some metavariables could not be solved: a proof must be given

0. F t ≡ F ?1
1. ?1: T
2. ?1: T
[.../Unif/Usage.lp:5:5-19] The proof is not finished.


```

**Comment by fblanqui** [comment]
@gabrielhdt Do you have an idea? Btw, I don't know how to get the decision trees for unif_rule ghost symbols.

**Comment by gabrielhdt** [comment]
> @gabrielhdt Do you have an idea? Btw, I don't know how to get the decision trees for unif_rule ghost symbols.

You mean from the command line with the `decision-tree` command? This feature is broken: we used to prefix ghost symbols with `#` but this is not relevant anymore since `#` is a valid character for the lexer. I'll fix this.

Regarding the unification rules, I guess it's a problem of signature loading or writing, but I haven't found anything fishy yet.

**Comment by fblanqui** [comment]
@gabrielhdt As you implemented unification rules, could you please take care of this issue?
