### ISSUE TITLE
Postfix / Assertnot syntax highlighting

### ISSUE THREAD

**Issue by qbuzet** [Deducteam/lambdapi#891]
In VSCode (but maybe in the other code editors too ?), postfix and assertnot are not colorized.

**Comment by GuillaumeGen** [comment]
For `assertnot`, it is due to a typo in https://github.com/Deducteam/lambdapi/blob/74a47238ce1d2d86a3a62c5e8100a6198e73564b/editors/vscode/syntaxes/lp.tmLanguage.json#L73
For `postfix, I assume that adding it to the whole list (line 28 of the file) and to the specific list for symbol modifier (line 78) should be sufficient.

**Comment by fblanqui** [comment]
Thanks @GuillaumeGen ! For postfix, I guess @gabrielhdt forgot it in #879 .

**Comment by fblanqui** [comment]
Fixed in #892
